# Generated by Django 4.0 on 2023-11-18 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'expert',
            },
        ),
        migrations.CreateModel(
            name='RtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='pathfinder_app/images/%Y/%m/%d')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'db_table': 'rt_image',
            },
        ),
        migrations.CreateModel(
            name='ExpertDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(max_length=20)),
                ('xmin', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymax', models.IntegerField()),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_defect_set', to='pathfinder_app.expert')),
                ('modifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
            options={
                'db_table': 'expert_defect',
            },
        ),
        migrations.AddField(
            model_name='expert',
            name='rt_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_set', to='pathfinder_app.rtimage'),
        ),
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model_name', models.CharField(max_length=20, null=True)),
                ('score', models.FloatField(null=True)),
                ('rt_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_model_set', to='pathfinder_app.rtimage')),
            ],
            options={
                'db_table': 'ai_model',
            },
        ),
        migrations.CreateModel(
            name='AiDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(max_length=20)),
                ('xmin', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymax', models.IntegerField()),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_defect_set', to='pathfinder_app.aimodel')),
            ],
            options={
                'db_table': 'ai_defect',
            },
        ),
    ]
