# Generated by Django 4.2.7 on 2023-12-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welder',
            name='others_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='welder',
            name='porosity_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='welder',
            name='slag_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
