# Generated by Django 4.0 on 2023-11-18 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathfinder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='rt_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert', to='pathfinder_app.rtimage'),
        ),
    ]
